### PR TITLE
smartphone styles

### PR DESCRIPTION
**Pull request by acmatl**
A media query is added to adapt the CO2 meter website to the smartphones screen, making the graphics to be put in columns when the screen width resolution goes below 640px.

### CODE REVIEW

**Comment by melkati** [comment]
Hi.

Thank you very much for your contribution to CO2 Gadget. It's very much appreciated. :-)

I'm right now working on a bug with WiFi. As soon as it gets sorted out I'll merge you PR.

Best regards!

**Comment by acmatl** [comment]
Update smartphone styles
adjusts the graphics column to the full hight of the screen

**Comment by melkati** [comment]
Good contribution!
Thank you! :-)

**Comment by acmatl** [comment]
Added web language.
Improved width and height adjustment of graphics, again.
Added provisional labels, with an initial style.

**Pull request merged**
